# Setup
title:            Creative Coding for Interactive Art
tagline:          
description:      Class notes, slides, resources.
url:              https://rvirmoors.github.io
baseurl:          /

author:
  name:           'Grigore Burloiu'
  url:            https://github.com/RVirmoors