# Setup
title:            Creative Coding for Interactive Art
tagline:          
description:      Class notes & resources for my courses @ ITPMA/UNATC.
# comment url & baseurl for local deploy
# see workflow @ https://tiefenauer.github.io/blog/gh-pages-plugins/
#url:              https://rvirmoors.github.io
#baseurl:          /

simple_search: http://google.com/search
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
git:
  branch: master

author:
  name:           'Grigore Burloiu'
  url:            https://github.com/RVirmoors